name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Update theme
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
        run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.69.0"

      - name: Build
        # remove --minify tag if you do not need it
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: nb-programmer/nb-programmer.github.io
          publish_dir: ./public
          keep_files: true
          user_name: nb-progrmmer
          user_email: narayanband1356@gmail.com
          publish_branch: master
        #   cname: example.com
